development:
  adapter: postgresql
  database: ttsmagic_development
  pool: 5
  timeout: 5000
  username: ttsmagic
  password:

test:
  adapter: postgresql
  database: ttsmagic_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ttsmagic_production
  pool: 5
  timeout: 5000
